src/main/java/com/cargaDescarga3/primefaces/bean/FileUploadView.java
package com.cargaDescarga3.primefaces.bean;

import com.cargaDescarga3.primefaces.presenter.FileUploadPresenter;
import com.cargaDescarga3.primefaces.utils.NavigatorUtil;
import lombok.Data;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;
import org.springframework.beans.factory.annotation.Autowired;

import javax.annotation.ManagedBean;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import java.io.IOException;

@ManagedBean
@Data
public class FileUploadView
{
    @Autowired
    private FileUploadPresenter fileUploadPresenter;

    private UploadedFile file;

    public void upload(long listId)
    {
        if (file != null)
        {
            FacesMessage message = new FacesMessage("Succesful", file.getFileName() + " is uploaded.");
            FacesContext.getCurrentInstance().addMessage(null, message);

            fileUploadPresenter.fileUploaded (file, listId);
        }
    }

    public void handleFileUpload(FileUploadEvent event)
    {
        Long listId = (Long) event.getComponent().getAttributes().get("listId");

        FacesMessage msg = new FacesMessage("Succesful", event.getFile().getFileName() + " is uploaded.");
        FacesContext.getCurrentInstance().addMessage(null, msg);

        fileUploadPresenter.fileUploaded (event.getFile(), listId);
    }
}

src/main/java/com/cargaDescarga3/primefaces/bean/HeaderViewBean.java
package com.cargaDescarga3.primefaces.bean;


import com.cargaDescarga3.primefaces.model.bean.UserBeanData;
import com.cargaDescarga3.primefaces.services.IUserLoggedService;
import com.cargaDescarga3.primefaces.utils.NavigatorUtil;
import lombok.Data;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.context.annotation.SessionScope;

import javax.annotation.PostConstruct;
import javax.inject.Named;

@Data
@Named
@SessionScope
public class HeaderViewBean
{
    private Logger logger = LoggerFactory.getLogger(HeaderViewBean.class);
    private UserBeanData user;

    @Autowired
    private IUserLoggedService userLoggedDataManager;

    private String headerURL = NavigatorUtil.GetHeaderURL();

    @PostConstruct
    void init()
    {
        logger.info("Creando objecto " + this);
        user = userLoggedDataManager.getLoggerUserBeanData();
    }
}

src/main/java/com/cargaDescarga3/primefaces/bean/ListUtisViewBean.java
package com.cargaDescarga3.primefaces.bean;

import com.cargaDescarga3.primefaces.enums.EstadoLista;
import com.cargaDescarga3.primefaces.enums.TipoLista;
import com.cargaDescarga3.primefaces.enums.TipoListaConsolidado;
import com.cargaDescarga3.primefaces.model.bean.ListBeanData;
import com.cargaDescarga3.primefaces.model.bean.UtiBeanData;
import com.cargaDescarga3.primefaces.services.IListDataService;
import com.cargaDescarga3.primefaces.services.IUtiDataService;
import lombok.Data;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;

import javax.annotation.PostConstruct;
import javax.faces.annotation.ManagedProperty;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

@Data
@Named
@ViewScoped
public class ListUtisViewBean implements Serializable
{
    @ManagedProperty("#{param.listId}")
    private Long listId;

    private String terminal;
    private Integer etd;
    private Integer eta;
    private Date created_date;
    private Date updated_date;
    private String updated_user;
    private Date closing_date;
    private String version;
    private EstadoLista state;
    private TipoLista circuit;
    private TipoListaConsolidado type;
    private String operator;
    private String visit_number;
    private String imo_code;
    private String call_sign;
    private String mmsi;
    private String flag;
    private String port;

    private List<UtiBeanData> utis;
    private List<UtiBeanData> utisFiltered;
    @Autowired
    private IUtiDataService utiDataService;
    @Autowired
    private IListDataService listDataManager;

    private Logger logger = LoggerFactory.getLogger(ListUtisViewBean.class);

    @PostConstruct
    public void init()
    {
        HttpServletRequest req = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
        listId = Long.parseLong(req.getParameter("listId"));

        logger.info("New ListUtisViewBean for list " + listId);

        ListBeanData list = listDataManager.getListBeanData(listId);

        terminal = list.getTerminal();
        created_date = list.getCreatedDate();
        updated_date = list.getUpdatedDate();
        closing_date = list.getClosingDate();
        version = list.getVersion();
        state = list.getState();
        circuit = list.getCircuit();
        type = list.getType();
        operator = list.getOperator();
        port = list.getPort();

        utis = utiDataService.getUtisForList(listId);
    }
}

src/main/java/com/cargaDescarga3/primefaces/bean/ListViewBean.java
package com.cargaDescarga3.primefaces.bean;

import com.cargaDescarga3.primefaces.model.bean.ListBeanData;
import com.cargaDescarga3.primefaces.model.bean.MainSummaryBeanData;
import com.cargaDescarga3.primefaces.model.bean.StopBeanData;
import com.cargaDescarga3.primefaces.enums.EstadoLista;
import com.cargaDescarga3.primefaces.enums.LoginType;
import com.cargaDescarga3.primefaces.enums.TipoLista;
import com.cargaDescarga3.primefaces.exceptions.SLCDCGeneralException;
import com.cargaDescarga3.primefaces.exceptions.NoValidStopException;
import com.cargaDescarga3.primefaces.presenter.ListViewBeanPresenter;
import com.cargaDescarga3.primefaces.utils.NavigatorUtil;
import lombok.Data;
import org.primefaces.event.ToggleEvent;
import org.primefaces.model.UploadedFile;
import org.primefaces.model.Visibility;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;

import javax.annotation.ManagedBean;
import javax.annotation.PostConstruct;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Data
@Named
@ViewScoped
@ManagedBean
public class ListViewBean implements Serializable
{
    @Autowired
    ListViewBeanPresenter listViewBeanPresenter;

    //TODO: No he terminado aquí. Esto de aquí abajo tengo que quitarlo y modificar todo esto para que funcione
    /*private ListData list_edit;
    private ListData create_list;
    private Long stop_id;*/
    //estadisticas

    private MainSummaryBeanData mainSummaryBeanData;
    //list
    private ListBeanData selected_list;
    //envia
    String updated_user;
    private LoginType sendTo;
    private String sendToPerson;
    //listas
    private java.util.List<ListBeanData> lists;
    private java.util.List<StopBeanData> stops;
    //private java.util.List<File> files;
    //condition
    private String conditionMessage;
    //cambio de stop
    private Long stop_a_buscar;
    private StopBeanData selectedStop;
    //Mensaje de error
    private String errMessage;
    private Logger logger = LoggerFactory.getLogger(ListViewBean.class);
    private Boolean[] visibleColumns;

    @PostConstruct
    public void init() throws IOException
    {
        visibleColumns = listViewBeanPresenter.getVisibleColumns();

        mainSummaryBeanData = new MainSummaryBeanData();

        boolean userLogged = listViewBeanPresenter.isAnyUserLogged();
        HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
        String parameterOne = request.getParameter("listId");
        if (parameterOne != null)
        {
            Long id = Long.valueOf(parameterOne);

            selected_list = listViewBeanPresenter.createListBeanData(id);
            selectedStop = selected_list.getStopBeanData();

            stop_a_buscar = selectedStop.getStopId();
        }
        else
        {
            selected_list = new ListBeanData();
            selectedStop = new StopBeanData();
        }

        if (lists == null)
        {
            lists = listViewBeanPresenter.getMyCreatedListsBeans();
        }
        if (stops == null)
        {
            stops = listViewBeanPresenter.getAllStops();
        }
        /*
        if (files == null)
        {
            files = listViewBeanPresenter.encontrarTodo();
        }
         */
    }

    //se usa
    public void addActionFile() throws IOException
    {
        boolean containerOperator = listViewBeanPresenter.hasLoggedUserRole("Container_Operator");
        if (containerOperator)
        {
            /*
            File file_to_delete = new File();
            for (File f : files)
            {
                if (f.getListId() == listViewBeanPresenter.findListById(selected_list.getId()))
                {
                    file_to_delete = f;
                }
            }

            listViewBeanPresenter.elimina(file_to_delete);
            File newFile = new File();
            newFile.setFile_name(file_src.getFileName());
            newFile.setFile_type(file_src.getContentType());
            newFile.setFile_size(file_src.getSize());
            newFile.setFile_src(file_src.getContents());
            newFile.setListId(listViewBeanPresenter.findListById(selected_list.getId()));
            listViewBeanPresenter.saveListData(newFile);
            String url = "listEdit.xhtml?listId=" + newFile.getListId().getListId();
            FacesContext.getCurrentInstance().getExternalContext().redirect(url);
            */
        }
        else
        {
            NavigatorUtil.RedirectToLists();
        }
    }

    public void cancelFile()
    {
        /*
        File file_to_delete = new File();
        for (File f : files)
        {
            if (f.getListId() == listViewBeanPresenter.findListById(selected_list.getId()))
            {
                file_to_delete = f;
            }
        }
        listViewBeanPresenter.elimina(file_to_delete);
        files = listViewBeanPresenter.encontrarTodo();

         */
    }

    //se usa
    public void downloadFile() throws IOException
    {
        /*
        java.io.File file_res;
        File file_todo = null;
        for (File f : files)
        {
            if (f.getListId() == listViewBeanPresenter.findListById(selected_list.getId()))
            {
                file_todo = f;
            }
        }
        if (file_todo != null)
        {
            //file
            file_res = new java.io.File(file_todo.getFile_name());
            FileUtils.writeByteArrayToFile(file_res, file_todo.getFile_src());
            //Content-Type
            String contentType = URLConnection.guessContentTypeFromName(file_res.getName());
            //Length
            String length = String.valueOf(file_res.length());
            //disposition
            String disposition = "attachment;filename=\"" + file_res.getName() + "\"";
            //data
            byte[] data = FileUtils.readFileToByteArray(file_res);
            //Enviar datos:
            FacesContext facesContext = FacesContext.getCurrentInstance();
            ExternalContext externalContext = facesContext.getExternalContext();
            externalContext.setResponseHeader("Content-Type", contentType);
            externalContext.setResponseHeader("Content-Length", length);
            externalContext.setResponseHeader("Content-Disposition", disposition);
            OutputStream outputStream = externalContext.getResponseOutputStream();
            outputStream.write(data);
            facesContext.responseComplete();
        }


         */
    }

    public java.util.List<ListBeanData> getLists()
    {
        if (lists == null)
        {
            return listViewBeanPresenter.getMyCreatedListsBeans();
        }

        int listPrep = 0;
        int listClosedPend = 0;

        for (ListBeanData l : lists)
        {
            if (l.getState() == EstadoLista.Pendiente)
            {
                listPrep++;
            }
            else
            {
                listClosedPend++;
            }
        }

        mainSummaryBeanData.setPreparingList(listPrep);
        mainSummaryBeanData.setClosedLists(listClosedPend);

        return lists;
    }

    public ListBeanData getList(Long id)
    {
        if (id == null)
        {
            throw new SLCDCGeneralException("No se dió ningun id a buscar");
        }
        if (lists != null)
        {
            selected_list = listViewBeanPresenter.createListBeanData(id);
            return selected_list;
        }
        return null;
    }

    public List<ListBeanData> getMyAcceptedLists()
    {

        List<ListBeanData> res = new ArrayList<>();

        /*
        List<ListData> myLists = getMyLists();

        for (ListData l : myLists)
        {
            AcceptList acceptList = listViewBeanPresenter.encontrarPorLista(l.getListId());
            if (acceptList != null)
            {
                if (acceptList.getAcceptBool())
                {
                    ListData lista = acceptList.getListId();
                    res.add(lista);
                }
            }
            else
            {
                AcceptList accept = new AcceptList();
                accept.setListId(l);
                accept.setAcceptBool(false);
                listViewBeanPresenter.guardarAcceptList(accept);
            }
        }

         */
        return res;
    }

    //se usa
    public List<ListBeanData> getMyNotAcceptedLists()
    {

        List<ListBeanData> res = new ArrayList<>();
        /*
        List<ListData> myLists = getMyLists();

        for (ListData l : myLists)
        {
            AcceptList acceptList = listViewBeanPresenter.encontrarPorLista(l.getListId());
            if (acceptList != null)
            {
                if (!acceptList.getAcceptBool())
                {
                    ListData lista  = acceptList.getListId();
                    res.add(lista);
                }
            }
            else
            {
                AcceptList accept = new AcceptList();
                accept.setListId(l);
                accept.setAcceptBool(false);
                listViewBeanPresenter.guardarAcceptList(accept);
                ListData lista  = acceptList.getListId();
                res.add(lista);
            }
        }

         */
        return res;
    }

    private List<ListBeanData> getMyLists()
    {
        List<ListBeanData> res = new ArrayList<>();

        // TODO: Es el dataManager correspondiente el que debe saber el usuario y devolver la lista adecuada
        /*
        listViewBeanPresenter.getMyCreatedListsRest();

        if (userDataManagerSpringSecurity.getRolesFromLoggerUser().contains(roleDataManager.findByName("Vessel Operator")))

src/main/java/com/cargaDescarga3/primefaces/model/Data.java
package com.cargaDescarga3.primefaces.model;


import com.cargaDescarga3.primefaces.enums.*;

import javax.annotation.ManagedBean;
import javax.enterprise.context.ApplicationScoped;

@ManagedBean
@ApplicationScoped
public class Data
{
    public Afirmacion[] getAfirmaciones()
    {
        return Afirmacion.values();
    }

    public Apertura[] getAperturas()
    {
        return Apertura.values();
    }

    public CircuitoUti[] getCircuitosUti()
    {
        return CircuitoUti.values();
    }

    public EstadoInforme[] getEstadosInforme()
    {
        return EstadoInforme.values();
    }

    public EstadoLista[] getEstadosLista()
    {
        return EstadoLista.values();
    }

    public EstadoUti[] getEstadosUti()
    {
        return EstadoUti.values();
    }

    public GrupoSustancia[] getGruposSustancia()
    {
        return GrupoSustancia.values();
    }

    public Temperatura[] getTemperaturas()
    {
        return Temperatura.values();
    }

    public TipoLista[] getTiposLista()
    {
        return TipoLista.values();
    }

    public TipoListaConsolidado[] getTiposListaConsolidado()
    {
        return TipoListaConsolidado.values();
    }

    public TipoPrecinto[] getTiposPrecinto()
    {
        return TipoPrecinto.values();
    }

    public TipoTransporte[] getTiposTransporte()
    {
        return TipoTransporte.values();
    }

    public LoginType[] getLoginType()
    {
        return LoginType.values();
    }

    public LoginType[] getEnvia()
    {
        return new LoginType[]{LoginType.Terminal, LoginType.Vessel_Operator};
    }
}

src/main/java/com/cargaDescarga3/primefaces/model/bean/ListBeanData.java
package com.cargaDescarga3.primefaces.model.bean;

import com.cargaDescarga3.primefaces.enums.EstadoLista;
import com.cargaDescarga3.primefaces.enums.TipoLista;
import com.cargaDescarga3.primefaces.enums.TipoListaConsolidado;
import lombok.Data;

import java.util.Date;

@Data
public class ListBeanData
{
    private Long id;

    private TipoLista circuit;
    private TipoListaConsolidado type;
    private String operator;
    private String port;
    private String terminal;
    private Date createdDate;
    private Date updatedDate;
    private Date closingDate;
    private String version;
    private EstadoLista state;

    private String username;
    private String visitNumber;

    private StopBeanData stopBeanData;
    private UserBeanData userBeanData;

}

src/main/webapp/header.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets" >

<header>
</header>

<body>
<h:form>
    <p:growl id="messages"/>

    <p:menubar>
        <p:submenu label="Lists">
            <p:menuitem value="Listas" url="lists.xhtml" />
            <p:menuitem value="Mis Listas" url="my_lists.xhtml" />
        </p:submenu>

        <p:menuitem value="Logout" url="logout" />

        <f:facet name="options">
            <p:inputText style="margin:1px 10px 1px 1px;" placeholder="Search"/>
            <h:outputText value="#{headerViewBean.user.username}" padding="5px"/>
        </f:facet>
    </p:menubar>

</h:form>
</body>

</html>

src/main/webapp/listAdd.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:pe="http://primefaces.org/ui/extensions">
    <h:head>
        <title>Lists Add - SLCDC</title>
        <link href="css/main.css" type="text/css" rel="stylesheet"/>
        <link href="css/style.css" type="text/css" rel="stylesheet"/>
    </h:head>

    <h:body>
            <ui:include src="header.xhtml"/>
            <p:messages id="messages" autoupdate="true" />

            <h:form id="form">
                <p:panel header="Nueva Lista" class="slcdc_panel">
                    <p:dataGrid class="slcdc_panel" id="list_table" var="lista" value="#{listViewBean.selected_list}">
                        <ui:include src="listGeneralInfo.xhtml"/>

                        <p:commandButton class="slcdc_button" value="Crear" action="#{listViewBean.addAction}" type="submit" />
                    </p:dataGrid>
                </p:panel>
            </h:form>

    </h:body>
</html>

src/main/webapp/listGeneralInfo.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
          xmlns:h="http://java.sun.com/jsf/html"
          xmlns:p="http://primefaces.org/ui"
          xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:panelGrid columns="2" layout="grid" style="margin-bottom:20px">
            <h:outputText value="Estancia: " />
            <p:selectOneMenu id="select_stop" value="#{listViewBean.stop_a_buscar}" disabled="#{listViewBean.isViewBeanInEditMode()}" styleClass="fullWidthComponent">
                <p:ajax listener="#{listViewBean.cambiaSelect}" update=":form:list_table" />
                <f:selectItem itemLabel="Estancia..." itemValue="" />
                <f:selectItems value="#{listViewBean.stops}" var="stop" itemLabel="#{stop.stopStringRepresentation}" itemValue="#{stop.stopId}" disabled="#{listViewBean.isViewBeanInEditMode()}"/>
            </p:selectOneMenu>

            <h:outputText value="Circuito: "/>
            <p:selectOneMenu id="circuit" value="#{lista.circuit}" unselectable="true" disabled="#{listViewBean.isViewBeanInEditMode()}" styleClass="fullWidthComponent">
                <f:selectItems value="#{data.tiposLista}"/>
            </p:selectOneMenu>

            <h:outputText value="Operator: "/>
            <p:inputText id="operator" value="#{lista.operator}" styleClass="fullWidthComponent"/>
    </h:panelGrid>

    <p:panelGrid columns="5" layout="grid" styleClass="panelGridColumnAtTop"  >
        <h:panelGrid columns="2" layout="grid">
            <f:facet name="header">
                <h:outputText value="List" styleClass="panelGridColumnHeader"/>
                <p:separator/>
            </f:facet>
            <h:outputText value="Terminal: " padding="100"/>
            <p:inputText id="terminal" value="#{lista.terminal}" styleClass="fullWidthComponent"/>

            <h:outputText value="Created date: "/>
            <p:calendar value="#{lista.createdDate}" disabled="true" styleClass="fullWidthComponent"/>

            <h:outputText value="Updated date: "/>
            <p:calendar value="#{lista.updatedDate}" disabled="true" styleClass="fullWidthComponent"/>

            <h:outputText value="Closing Date: "/>
            <p:calendar value="#{lista.closingDate}" disabled="true" styleClass="fullWidthComponent"/>

            <h:outputText value="Version: "/>
            <p:inputText id="version" value="#{lista.version}" disabled="true" styleClass="fullWidthComponent"/>

            <h:outputText value="State: "/>
            <p:selectOneMenu id="state" value="#{lista.state}" unselectable="true" styleClass="fullWidthComponent">
                <f:selectItems value="#{data.estadosLista}"/>
            </p:selectOneMenu>

            <h:outputText value="Tipo Lista: "/>
            <p:selectOneMenu id="type" value="#{lista.type}" unselectable="true" styleClass="fullWidthComponent">
                <f:selectItems value="#{data.tiposListaConsolidado}"/>
            </p:selectOneMenu>

            <h:outputText value="Port: "/>
            <p:inputText id="port" value="#{lista.port}" disabled="true" styleClass="fullWidthComponent"/>
        </h:panelGrid>

        <h:panelGrid id="visit" columns="2" layout="grid">
            <f:facet name="header">
                <h:outputText value="Visit" styleClass="panelGridColumnHeader"/>
                <p:separator/>
            </f:facet>
            <h:outputText value="Código del siguiente puerto: "/>
            <p:inputText id="nextPort_code" value="#{listViewBean.selectedStop.visitNextPortCode}" disabled="true" />

            <h:outputText value="Visit ETA: "/>
            <p:calendar id="visit_eta"  value="#{listViewBean.selectedStop.visitEta}" disabled="true" />

            <h:outputText value="Visit ETD: "/>
            <p:calendar id="visit_etd"  value="#{listViewBean.selectedStop.visitEtd}" disabled="true" />

            <h:outputText value="Visit ATA: "/>
            <p:calendar id="visit_ata"  value="#{listViewBean.selectedStop.visitAta}" disabled="true" />

            <h:outputText value="Visit ATD: "/>
            <p:calendar id="visit_atd"  value="#{listViewBean.selectedStop.visitAtd}" disabled="true" />

            <h:outputText value="Visit Status ID: "/>
            <p:inputText id="visit_status_id" value="#{listViewBean.selectedStop.visitStatusId}" disabled="true" />

            <h:outputText value="Visit number: "/>
            <p:inputText id="visit_number" value="#{listViewBean.selectedStop.visitNumber}" disabled="true" />
        </h:panelGrid>

        <h:panelGrid id="stop" columns="2" layout="grid">
            <f:facet name="header">
                <h:outputText value="Estancia" styleClass="panelGridColumnHeader"/>
                <p:separator/>
            </f:facet>
            <h:outputText value="Stop ETA: "/>
            <p:calendar id="stop_eta"  value="#{listViewBean.selectedStop.stopEta}" disabled="true" />

            <h:outputText value="Stop ETD: "/>
            <p:calendar id="stop_etd"  value="#{listViewBean.selectedStop.stopEtd}" disabled="true" />

            <h:outputText value="Stop ATA: "/>
            <p:calendar id="stop_ata"  value="#{listViewBean.selectedStop.stopAta}" disabled="true" />

            <h:outputText value="Stop ATD: "/>
            <p:calendar id="stop_atd"  value="#{listViewBean.selectedStop.stopAtd}" disabled="true" />
        </h:panelGrid>

        <h:panelGrid id="ship" columns="2" layout="grid">
            <f:facet name="header">
                <h:outputText value="Ship" styleClass="panelGridColumnHeader"/>
                <p:separator/>
            </f:facet>
            <h:outputText value="Call Sign: "/>
            <p:inputText id="call_sign" value="#{listViewBean.selectedStop.shipCallSign}" disabled="true"/>

            <h:outputText value="Flag: "/>
            <p:inputText id="flag" value="#{listViewBean.selectedStop.shipFlag}" disabled="true" />

            <h:outputText value="IMO Code: "/>
            <p:inputText id="imo_code" value="#{listViewBean.selectedStop.shipImo}" disabled="true" />

            <h:outputText value="MMSI: "/>
            <p:inputText id="mmsi" value="#{listViewBean.selectedStop.shipMmsi}" disabled="true" />

            <h:outputText value="Nombre del barco: "/>
            <p:inputText id="ship_name" value="#{listViewBean.selectedStop.shipName}" disabled="true" />
        </h:panelGrid>

        <h:panelGrid id="agent" columns="2" layout="grid">
            <f:facet name="header">
                <h:outputText value="Agent" styleClass="panelGridColumnHeader"/>
                <p:separator/>
            </f:facet>
            <h:outputText value="CIF del agente: "/>
            <p:inputText id="agent_cif" value="#{listViewBean.selectedStop.agentCif}" disabled="true" />

            <h:outputText value="Nombre del agente: "/>
            <p:inputText id="agent_name" value="#{listViewBean.selectedStop.agentName}" disabled="true" />
        </h:panelGrid>

    </p:panelGrid>
</html>

src/main/webapp/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pe="http://primefaces.org/ui/extensions">

<h:head>
    <title>Login</title>
</h:head>

<h:body>
        <h:form prependId="false">

            <p:panelGrid columns="1" styleClass="ui-fluid center ui-noborder">
                <h2>Please login</h2>

                <p:outputLabel value="Login failed!" styleClass="red"
                               rendered="${!empty param['error']}" />

                <p:inputText id="username" placeholder="Username" />
                <p:password id="password" placeholder="Password" />

                <p:commandButton id="loginButton" value="Login" ajax="false" />
            </p:panelGrid>

        </h:form>

</h:body>
</html>